theme = "custom_theme"

[editor]
line-number = "relative"
mouse = true
cursorline = true
auto-pairs = false
auto-format = false
scrolloff = 10        
bufferline = "always"
true-color = true
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = false

[editor.statusline]
right = [
    "version-control",
    "file-encoding",
    "file-type",
    "file-line-ending",
    "separator",
    "file-name",
    "read-only-indicator",
    "separator",
    "spacer",
    "file-modification-indicator",
]
left = [
    "mode",
    "selections",
    "primary-selection-length",
    "separator",
    "position",
    "position-percentage",
]
center = ["spinner", "diagnostics", "separator", "workspace-diagnostics"]

[editor.statusline.mode]
insert = "INSERT"
normal = "NORMAL"
select = "SELECT"

[keys.normal.space]
w = ":w"
q = ":buffer-close"

[keys.select.space]
w = ":w"
q = ":buffer-close"

[keys.normal]
A-w = ":w"            
A-q = ":buffer-close" 
A-f = ":format"           
A-h = ":bp"
A-l = ":bn"
"A-/" = ["toggle_comments", "move_line_down"]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
C-e = [":insert-output yazi %{buffer_name}", ":redraw"]
Y = ["extend_to_line_end", "yank", "collapse_selection"]

[keys.select]
A-f = ":format"           
A-h = ":bp"
A-l = ":bn"
"A-/" = ["toggle_comments", "move_line_down"]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
C-e = [":insert-output yazi %{buffer_name}", ":redraw"]
