theme = "custom_theme"

[editor]
line-number = "relative"
mouse = true
cursorline = true
auto-pairs = false
scrolloff = 10        
bufferline = "always"
true-color = true
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = false

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "â”‚"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]

[keys.normal.space]
c = ["toggle_comments", "move_line_down"]
w = ":w"
q = ":buffer-close"

[keys.select.space]
c = ["toggle_comments", "move_line_down"]
w = ":w"
q = ":buffer-close"

[keys.normal]
A-w = ":w"            
A-q = ":buffer-close" 
"C-[" = "normal_mode"
A-f = ":format"           
A-h = ":bp"
A-l = ":bn"
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]

[keys.insert]
"C-[" = "normal_mode"

[keys.select]
A-f = ":format"           
A-h = ":bp"
A-l = ":bn"
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
