inherits = "material_oceanic"
# inherits = "varua"

"ui.cursor" = { fg = "#000000", bg = "#FFFF00" }        # normalny tryb: czarny znak na żółtym tle
"ui.cursor.insert" = { bg = "#FF0000" }                # tryb insert: żółte tło
"ui.cursor.select" = { bg = "#FFFF00" }                # tryb select: żółte tło
